name: pdfjs
version: 2.1.266+4

description: Dart bindings for Mozilla's PDF.js library

homepage: https://github.com/Workiva/pdfjs_dart

authors:
  - Sean Burke <sean.burke@workiva.com>

environment:
  sdk: '>=1.24.0 <3.0.0'
